sudo: required
services:
  - docker

install: 
  - docker build -t elkhadri4/multi-client ./client
  - docker build -t elkhadri4/multi-nginx ./nginx
  - docker build -t elkhadri4/multi-server ./server
  - docker build -t elkhadri4/multi-worker ./worker
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push elkhadri4/multi-client
  - docker push elkhadri4/multi-nginx
  - docker push elkhadri4/multi-server
  - docker push elkhadri4/multi-worker