sudo: required
services:
  - docker

before_install:
  - docker build -t elkhadri4/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true elkhadri4/react-test npm test

after_success:
  - docker build -t elkhadri4/multi-client ./client
  - docker build -t elkhadri4/multi-nginx ./nginx
  - docker build -t elkhadri4/multi-server ./server
  - docker build -t elkhadri4/multi-worker ./worker
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push elkhadri4/multi-client
  - docker push elkhadri4/multi-nginx
  - docker push elkhadri4/multi-server
  - docker push elkhadri4/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-container"
  env: "MultiContainer-env "
  bucket_name: "elasticbeanstalk-eu-west-3-874977614950"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY